### ISSUE TITLE
Open source dataset

### ISSUE THREAD

**Issue by aadimator** [harisbinzia/PronouncUR#1]
Would you please open source your dataset so as to move the research in this area forward? It would be much appreciated. One of the bottlenecks in the research in the Urdu language is the scarcity of the available dataset.

**Comment by harisbinzia** [comment]
Hi, thanks for your interest in PronouncUR. Due to some proprietary constraints we won't be able to share our dataset. However, feel free to use our G2P model to quickly generate training data for your own model. Best of luck.
-Haris
